FROM registry.access.redhat.com/ubi9/python-312:latest

USER 0

RUN dnf update -y && \
    dnf -y install clang rpm-build git ninja-build cmake lld && \
    dnf clean all && rm -rf /var/cache/dnf
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install --upgrade cmake ninja sccache
RUN git clone https://github.com/llvm/llvm-project /llvm-project
WORKDIR /llvm-project
RUN python3 -m pip install -r mlir/python/requirements.txt
