name: cpu-image

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/cpu-image.yml
      - Dockerfile.triton-cpu
      - entrypoint.sh
      - users.sh
  pull_request:
    paths:
      - .github/workflows/cpu-image.yml
      - Dockerfile.triton-cpu
      - entrypoint.sh
      - users.sh
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  cpu-image-build:
    uses: ./.github/workflows/image-build.yml
    with:
      image-name: cpu
      image-tag: latest
      dockerfile: Dockerfile.triton-cpu
      build-args: |
        USERNAME=triton
        CUSTOM_LLVM=false
      platforms: linux/amd64
    secrets:
      qt_username: ${{ secrets.qt_username }}
      qt_password: ${{ secrets.qt_password }}

  cpu-image-sbom:
    needs: cpu-image-build
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/image-sbom.yml
    with:
      image-name: cpu
      image-tag: latest
    secrets:
      qt_username: ${{ secrets.qt_username }}
      qt_password: ${{ secrets.qt_password }}
