name: cpu-image

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/cpu-image.yml
      - Dockerfile.triton-cpu
      - entrypoint.sh
      - users.sh
  pull_request:
    paths:
      - .github/workflows/cpu-image.yml
      - Dockerfile.triton-cpu
      - entrypoint.sh
      - users.sh
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  cpu-image_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - IMAGE_NAME: cpu
            IMAGE_FILE: Dockerfile.triton-cpu
            PLATFORMS: linux/amd64
            LABEL: latest
            BUILD_ARGS: |
              USERNAME=triton
              CUSTOM_LLVM=false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # NOTE:  setting fetch-depth to 0 to retrieve the entire history
          # instead of a shallow-clone so that all tags are fetched as well.
          # This is necessary for computing the VERSION using `git describe`
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v8.1.5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up cosign
        uses: sigstore/cosign-installer@main

      - name: Login to Quay
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: docker/login-action@v3
        with:
          registry: quay.io/triton-dev-containers
          username: ${{ secrets.qt_username }}
          password: ${{ secrets.qt_password }}

      - name: Build and (conditionally) push image
        id: build-push-image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.PLATFORMS }}
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: quay.io/triton-dev-containers/${{ matrix.IMAGE_NAME }}:${{ matrix.LABEL }}
          labels: ${{ matrix.LABEL }}
          build-args: ${{matrix.BUILD_ARGS}}
          file: ${{ matrix.IMAGE_FILE }}

      - name: Sign images with GitHub OIDC Token
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: |
          cosign sign -y quay.io/triton-dev-containers/${{ matrix.IMAGE_NAME }}:${{ matrix.LABEL }}@${{ steps.build-push-image.outputs.digest }}

      - name: Generate image attestation
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

        uses: actions/attest-build-provenance@v2
        with:
          subject-name: quay.io/triton-dev-containers/${{ matrix.IMAGE_NAME }}
          subject-digest: ${{ steps.build-push-image.outputs.digest }}
          push-to-registry: true

      - name: Generate SBOM
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: anchore/sbom-action@v0.18.0
        with:
          image: quay.io/triton-dev-containers/${{ matrix.IMAGE_NAME }}:${{ matrix.LABEL }}
          artifact-name: sbom-${{ matrix.IMAGE_NAME }}-${{ matrix.LABEL }}.json
          output-file: ./sbom-${{ matrix.IMAGE_NAME }}-${{ matrix.LABEL }}.spdx.json

      - name: Generate SBOM attestation with Cosign with GitHub OIDC Token
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: |
          cosign attest -y --predicate ./sbom-${{ matrix.IMAGE_NAME }}-${{ matrix.LABEL }}.spdx.json --type spdxjson quay.io/triton-dev-containers/${{ matrix.IMAGE_NAME }}:${{ matrix.LABEL }}@${{ steps.build-push-image.outputs.digest }}

      - name: Compress SBOM
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: gzip ./sbom-${{ matrix.IMAGE_NAME }}-${{ matrix.LABEL }}.spdx.json

      - name: Save Triton-cpu image SBOM as artifact
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4.6.0
        with:
          name: sbom-${{ matrix.IMAGE_NAME }}-${{ matrix.LABEL }}.spdx.json.gz
          path: ./sbom-${{ matrix.IMAGE_NAME }}-${{ matrix.LABEL }}.spdx.json.gz
          retention-days: 1
