name: Validate Triton-CPU DevContainer

on:
  pull_request: # yamllint disable-line rule:truthy
    paths:
      - '.devcontainer/triton-cpu/**'
      - '.devcontainer/scripts/generate-devcontainers.sh'
      - '.devcontainer/base/**'
      - '.github/workflows/validate-devcontainer.yml'
  push:
    branches:
      - main

jobs:
  validate-devcontainer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dev Container CLI
        run: npm install -g @devcontainers/cli

      - name: Install Make
        run: sudo apt-get install -y make

      - name: Generate triton-cpu devcontainer
        run: make generate v=triton-cpu

      - name: Validate triton-cpu devcontainer
        run: |
          devcontainer build --workspace-folder . --config triton-cpu/devcontainer.json
          devcontainer run --workspace-folder . --config triton-cpu/devcontainer.json -- echo "✅ Triton-CPU dev container works!"
