name: cuda-image

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/cuda-image.yml
      - dockerfiles/Dockerfile.cuda
      - scripts/entrypoint.sh
      - scripts/devinstall_software.sh
      - scripts/ldpretend.sh
      - scripts/devinstall_llvm.sh
      - scripts/devinstall_torch.sh
      - scripts/devinstall_helion.sh
      - scripts/devinstall_triton.sh
      - scripts/devinstall_vllm.sh
      - scripts/devcreate_user.sh
      - scripts/devsetup.sh
  pull_request:
    paths:
      - .github/workflows/cuda-image.yml
      - dockerfiles/Dockerfile.cuda
      - scripts/entrypoint.sh
      - scripts/devinstall_software.sh
      - scripts/ldpretend.sh
      - scripts/devinstall_llvm.sh
      - scripts/devinstall_torch.sh
      - scripts/devinstall_helion.sh
      - scripts/devinstall_triton.sh
      - scripts/devinstall_vllm.sh
      - scripts/devcreate_user.sh
      - scripts/devsetup.sh
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  base-image-build:
    uses: ./.github/workflows/image-build.yml
    with:
      image-name: base
      image-tag: centos10
      dockerfile: dockerfiles/Dockerfile
      platforms: linux/amd64
    secrets:
      qt_username: ${{ secrets.qt_username }}
      qt_password: ${{ secrets.qt_password }}

  cuda-image-build:
    needs: base-image-build
    uses: ./.github/workflows/image-build.yml
    with:
      image-name: cuda
      image-tag: 13-2-centos10
      dockerfile: dockerfiles/Dockerfile.cuda
      build-args: |
        USERNAME=triton
        BUILD_CUDA_VERSION=13-2
      platforms: linux/amd64
    secrets:
      qt_username: ${{ secrets.qt_username }}
      qt_password: ${{ secrets.qt_password }}

  cuda-image-sbom:
    needs: cuda-image-build
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/image-sbom.yml
    with:
      image-name: cuda
      image-tag: 13-2-centos10
    secrets:
      qt_username: ${{ secrets.qt_username }}
      qt_password: ${{ secrets.qt_password }}
