name: gosu-image

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/gosu-image.yml
      - Dockerfile.gosu
  pull_request:
    paths:
      - .github/workflows/gosu-image.yml
      - Dockerfile.gosu
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  gosu-image-build:
    uses: ./.github/workflows/image-build.yml
    with:
      image-name: gosu
      image-tag: latest
      dockerfile: Dockerfile.gosu
      platforms: linux/amd64
    secrets:
      qt_username: ${{ secrets.qt_username }}
      qt_password: ${{ secrets.qt_password }}

  gosu-image-sbom:
    needs: gosu-image-build
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/image-sbom.yml
    with:
      image-name: gosu
      image-tag: latest
    secrets:
      qt_username: ${{ secrets.qt_username }}
      qt_password: ${{ secrets.qt_password }}
