name: llvm-image

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/llvm-image.yml
      - Dockerfile.llvm
  pull_request:
    paths:
      - .github/workflows/llvm-image.yml
      - Dockerfile.llvm
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  llvm-image-build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - image-name: llvm
            image-tag: latest
            dockerfile: Dockerfile.llvm
            platforms: linux/amd64
            build-args: |
              CUSTOM_LLVM=true
              TRITON_CPU_BACKEND=0
          - image-name: llvm
            image-tag: cpu-latest
            dockerfile: Dockerfile.llvm
            platforms: linux/amd64
            build-args: |
              CUSTOM_LLVM=true
              TRITON_CPU_BACKEND=1
    uses: ./.github/workflows/image-build.yml
    with:
      image-name: ${{ matrix.image-name }}
      image-tag: ${{ matrix.image-tag }}
      dockerfile: ${{ matrix.dockerfile }}
      platforms: ${{ matrix.platforms }}
      build-args: ${{ matrix.build-args }}
    secrets:
      qt_username: ${{ secrets.qt_username }}
      qt_password: ${{ secrets.qt_password }}

  llvm-image-sbom:
    needs: llvm-image-build
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        include:
          - image-name: llvm
            image-tag: latest
          - image-name: llvm
            image-tag: cpu-latest
    uses: ./.github/workflows/image-sbom.yml
    with:
      image-name: ${{ matrix.image-name }}
      image-tag: ${{ matrix.image-tag }}
    secrets:
      qt_username: ${{ secrets.qt_username }}
      qt_password: ${{ secrets.qt_password }}
