name: nvidia-image

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/nvidia-image.yml
      - Dockerfile.triton
      - entrypoint.sh
      - users.sh
  pull_request:
    paths:
      - .github/workflows/nvidia-image.yml
      - Dockerfile.triton
      - entrypoint.sh
      - users.sh
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  nvidia-image-build:
    uses: ./.github/workflows/image-build.yml
    with:
      image-name: nvidia
      image-tag: latest
      dockerfile: Dockerfile.triton
      build-args: |
        USERNAME=triton
        CUSTOM_LLVM=false
        INSTALL_CUDNN=true
      platforms: linux/amd64
    secrets:
      qt_username: ${{ secrets.qt_username }}
      qt_password: ${{ secrets.qt_password }}

  nvidia-image-sbom:
    needs: nvidia-image-build
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/image-sbom.yml
    with:
      image-name: nvidia
      image-tag: latest
    secrets:
      qt_username: ${{ secrets.qt_username }}
      qt_password: ${{ secrets.qt_password }}
